[package]
name = "rayromano"
version = "0.1.0"
edition = "2021"
authors = ["Alexis Williams <alexis@typedr.at>"]
license = "MIT OR Apache-2.0"

[dependencies]
gtk = { version = "0.8.2", package = "gtk4", features = ["v4_14"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
